# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/santos10-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/liboclcompiler.so:system/vendor/lib/liboclcompiler.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libPVROCL.so:system/vendor/lib/libPVROCL.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libsrv_init.so:system/vendor/lib/libsrv_init.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libusc.so:system/vendor/lib/libusc.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/egl/libEGL_POWERVR_SGX544_115.so:system/vendor/lib/egl/libEGL_POWERVR_SGX544_115.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX544_115.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX544_115.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/egl/libGLESv2_POWERVR_SGX544_115.so:system/vendor/lib/egl/libGLESv2_POWERVR_SGX544_115.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/hw/gralloc.clovertrail.so:system/vendor/lib/hw/gralloc.clovertrail.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/hw/memtrack.clovertrail.so:system/vendor/lib/hw/memtrack.clovertrail.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libmultidisplay.so:system/vendor/lib/libmultidisplay.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libsepdrm.so:system/vendor/lib/libsepdrm.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libmixvbp.so:system/vendor/lib/libmixvbp.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libmixvbp_h264.so:system/vendor/lib/libmixvbp_h264.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libmixvbp_mpeg4.so:system/vendor/lib/libmixvbp_mpeg4.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libpvr2d.so:system/vendor/lib/libpvr2d.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libia_aiq.so:system/vendor/lib/libia_aiq.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libia_aiq_cp.so:system/vendor/lib/libia_aiq_cp.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libia_mkn.so:system/vendor/lib/libia_mkn.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libia_nvm.so:system/vendor/lib/libia_nvm.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libmfldadvci.so:system/vendor/lib/libmfldadvci.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libsecnativefeature.so:system/vendor/lib/libsecnativefeature.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libtbd.so:system/vendor/lib/libtbd.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/hw/audio.primary.clovertrail.so:system/vendor/lib/hw/audio.primary.clovertrail.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libaudio-ril.so:system/vendor/lib/libaudio-ril.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libsamsungearcare.so:system/vendor/lib/libsamsungearcare.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libsamsungRecord.so:system/vendor/lib/libsamsungRecord.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libsamsungRecord_ns.so:system/vendor/lib/libsamsungRecord_ns.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libsamsungSoundbooster.so:system/vendor/lib/libsamsungSoundbooster.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/lib_SamsungEP_V02014.so:system/vendor/lib/lib_SamsungEP_V02014.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/lib_SamsungRecNR_V02023d.so:system/vendor/lib/lib_SamsungRecNR_V02023d.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/lib_SamsungRec_V02003.so:system/vendor/lib/lib_SamsungRec_V02003.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/lib_Samsung_Resampler_V01004b.so:system/vendor/lib/lib_Samsung_Resampler_V01004b.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/lib_Samsung_SB_AM_V04005_20130729.so:system/vendor/lib/lib_Samsung_SB_AM_V04005_20130729.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/santos10-common/proprietary/vendor/bin/geomagneticd:system/vendor/bin/geomagneticd \
    vendor/samsung/santos10-common/proprietary/vendor/bin/orientationd:system/vendor/bin/orientationd \
    vendor/samsung/santos10-common/proprietary/vendor/lib/hw/keystore.vendor.clovertrail.so:system/vendor/lib/hw/keystore.vendor.clovertrail.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libsepkeymaster.so:system/vendor/lib/libsepkeymaster.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libcrypto_stock.so:system/vendor/lib/libcrypto_stock.so \
    vendor/samsung/santos10-common/proprietary/vendor/lib/libssl_stock.so:system/vendor/lib/libssl_stock.so \
    vendor/samsung/santos10-common/proprietary/vendor/firmware/fw_sst_08e7.bin:system/vendor/firmware/fw_sst_08e7.bin \
    vendor/samsung/santos10-common/proprietary/vendor/firmware/topazsc_fw.bin:system/vendor/firmware/topazsc_fw.bin \
    vendor/samsung/santos10-common/proprietary/vendor/firmware/shisp_css15.bin:system/vendor/firmware/shisp_css15.bin \
    vendor/samsung/santos10-common/proprietary/etc/firmware/isp_fr.bin:system/etc/firmware/isp_fr.bin \
    vendor/samsung/santos10-common/proprietary/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
    vendor/samsung/santos10-common/proprietary/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv \
    vendor/samsung/santos10-common/proprietary/vendor/firmware/bcmdhd_sta.bin_b2:system/vendor/firmware/bcmdhd_sta.bin_b2 \
    vendor/samsung/santos10-common/proprietary/vendor/firmware/bcmdhd_apsta.bin_b2:system/vendor/firmware/bcmdhd_apsta.bin_b2 \
    vendor/samsung/santos10-common/proprietary/vendor/firmware/nvram_net.txt:system/vendor/firmware/nvram_net.txt \
    vendor/samsung/santos10-common/proprietary/vendor/firmware/bcm4334.hcd:system/vendor/firmware/bcm4334.hcd
